//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWPF.AdminServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Learner", Namespace="http://schemas.datacontract.org/2004/07/SportSchoolClassLibrary")]
    [System.SerializableAttribute()]
    public partial class Learner : TestWPF.AdminServiceReference.Person {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime BirthDateField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime BirthDate {
            get {
                return this.BirthDateField;
            }
            set {
                if ((this.BirthDateField.Equals(value) != true)) {
                    this.BirthDateField = value;
                    this.RaisePropertyChanged("BirthDate");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Person", Namespace="http://schemas.datacontract.org/2004/07/SportSchoolClassLibrary")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TestWPF.AdminServiceReference.Instructor))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TestWPF.AdminServiceReference.Learner))]
    public partial class Person : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MiddleNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SectionIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SurnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelephoneNumberField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MiddleName {
            get {
                return this.MiddleNameField;
            }
            set {
                if ((object.ReferenceEquals(this.MiddleNameField, value) != true)) {
                    this.MiddleNameField = value;
                    this.RaisePropertyChanged("MiddleName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SectionID {
            get {
                return this.SectionIDField;
            }
            set {
                if ((this.SectionIDField.Equals(value) != true)) {
                    this.SectionIDField = value;
                    this.RaisePropertyChanged("SectionID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Surname {
            get {
                return this.SurnameField;
            }
            set {
                if ((object.ReferenceEquals(this.SurnameField, value) != true)) {
                    this.SurnameField = value;
                    this.RaisePropertyChanged("Surname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TelephoneNumber {
            get {
                return this.TelephoneNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.TelephoneNumberField, value) != true)) {
                    this.TelephoneNumberField = value;
                    this.RaisePropertyChanged("TelephoneNumber");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Instructor", Namespace="http://schemas.datacontract.org/2004/07/SportSchoolClassLibrary")]
    [System.SerializableAttribute()]
    public partial class Instructor : TestWPF.AdminServiceReference.Person {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AdminServiceReference.IAdminService")]
    public interface IAdminService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminService/GetLeranersBy", ReplyAction="http://tempuri.org/IAdminService/GetLeranersByResponse")]
        TestWPF.AdminServiceReference.Learner[] GetLeranersBy(string section);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminService/GetLeranersBy", ReplyAction="http://tempuri.org/IAdminService/GetLeranersByResponse")]
        System.Threading.Tasks.Task<TestWPF.AdminServiceReference.Learner[]> GetLeranersByAsync(string section);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminService/GetInstructorsBy", ReplyAction="http://tempuri.org/IAdminService/GetInstructorsByResponse")]
        TestWPF.AdminServiceReference.Instructor[] GetInstructorsBy(string section);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminService/GetInstructorsBy", ReplyAction="http://tempuri.org/IAdminService/GetInstructorsByResponse")]
        System.Threading.Tasks.Task<TestWPF.AdminServiceReference.Instructor[]> GetInstructorsByAsync(string section);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminService/InsertNewInstructor", ReplyAction="http://tempuri.org/IAdminService/InsertNewInstructorResponse")]
        void InsertNewInstructor(TestWPF.AdminServiceReference.Instructor instructor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminService/InsertNewInstructor", ReplyAction="http://tempuri.org/IAdminService/InsertNewInstructorResponse")]
        System.Threading.Tasks.Task InsertNewInstructorAsync(TestWPF.AdminServiceReference.Instructor instructor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminService/InsertNewLearner", ReplyAction="http://tempuri.org/IAdminService/InsertNewLearnerResponse")]
        void InsertNewLearner(TestWPF.AdminServiceReference.Learner learner);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminService/InsertNewLearner", ReplyAction="http://tempuri.org/IAdminService/InsertNewLearnerResponse")]
        System.Threading.Tasks.Task InsertNewLearnerAsync(TestWPF.AdminServiceReference.Learner learner);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminService/GetSectionID", ReplyAction="http://tempuri.org/IAdminService/GetSectionIDResponse")]
        int GetSectionID(string section);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminService/GetSectionID", ReplyAction="http://tempuri.org/IAdminService/GetSectionIDResponse")]
        System.Threading.Tasks.Task<int> GetSectionIDAsync(string section);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAdminServiceChannel : TestWPF.AdminServiceReference.IAdminService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AdminServiceClient : System.ServiceModel.ClientBase<TestWPF.AdminServiceReference.IAdminService>, TestWPF.AdminServiceReference.IAdminService {
        
        public AdminServiceClient() {
        }
        
        public AdminServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AdminServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AdminServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AdminServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public TestWPF.AdminServiceReference.Learner[] GetLeranersBy(string section) {
            return base.Channel.GetLeranersBy(section);
        }
        
        public System.Threading.Tasks.Task<TestWPF.AdminServiceReference.Learner[]> GetLeranersByAsync(string section) {
            return base.Channel.GetLeranersByAsync(section);
        }
        
        public TestWPF.AdminServiceReference.Instructor[] GetInstructorsBy(string section) {
            return base.Channel.GetInstructorsBy(section);
        }
        
        public System.Threading.Tasks.Task<TestWPF.AdminServiceReference.Instructor[]> GetInstructorsByAsync(string section) {
            return base.Channel.GetInstructorsByAsync(section);
        }
        
        public void InsertNewInstructor(TestWPF.AdminServiceReference.Instructor instructor) {
            base.Channel.InsertNewInstructor(instructor);
        }
        
        public System.Threading.Tasks.Task InsertNewInstructorAsync(TestWPF.AdminServiceReference.Instructor instructor) {
            return base.Channel.InsertNewInstructorAsync(instructor);
        }
        
        public void InsertNewLearner(TestWPF.AdminServiceReference.Learner learner) {
            base.Channel.InsertNewLearner(learner);
        }
        
        public System.Threading.Tasks.Task InsertNewLearnerAsync(TestWPF.AdminServiceReference.Learner learner) {
            return base.Channel.InsertNewLearnerAsync(learner);
        }
        
        public int GetSectionID(string section) {
            return base.Channel.GetSectionID(section);
        }
        
        public System.Threading.Tasks.Task<int> GetSectionIDAsync(string section) {
            return base.Channel.GetSectionIDAsync(section);
        }
    }
}
